Feature/zcs 3128
Zimbra/oauth2_datasources pull request #3
Opened 2017-10-10 16:13 UTC by grishick

With these changes, the extension can be used for testing. What's left is more testing for followup synchronization.

2017-10-11 19:03 UTC, tmclane approved these changes

2017-10-11 19:19 UTC, desouzas approved these changes

2017-10-12 09:56 UTC, fatkudu approved these changes
Looks good.  Couple of queries about possible future improvements.

2017-10-12 09:56 UTC, fatkudu commented on src/java/com/synacor/zimbra/ys/contacts/YahooContactsImport.java
> +            response = client.execute(get);
Is there a way to log the request and response should that be desired?

2017-10-12 09:56 UTC, fatkudu commented on src/java/com/synacor/zimbra/ys/contacts/YahooContactsUtil.java
> +                                    ZimbraLog.extensions.warn("YahooContactsUtil cannot map Yahoo Contact field of type '%s' to any Zimbra contact field. Ignoring the field.", fieldType);
I'm sure contacts has a way to store unknown data with some kind of key=value mechanism??

2017-10-13 10:39 UTC, fatkudu requested changes
If you export your contacts to CSV, then edit the target file and add some randomly named fields at the end - say "Wibble" and "Wobble", then add some values for those fields for a contact - say - "Potato" and "Waffles", then import that into another account, the UI shows those fields in an Other category, with the values in one column and field name in another.  This way you preserve both the old field name and the value rather than just the value.

2017-10-13 17:30 UTC, merged